name: vikrant
on:
  workflow_dispatch:
       
 
    
env:
  aws-region: us-east-1

jobs:
  terraform_pipeline_destroy:
    name: vikrant
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3
        with:
          timeout-minutes: 5 

        
      
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1   
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          Aws-region: ${{env.aws-region}}
      # - name: Start Session Manager session
      #   run: |
      #     aws ssm start-session --target i-071a4716e15bd8b94
      - name: Copy file to Windows server
        # run: |
        #   cd C:\actions-runner\_work\
        #   scp -i ./Test-discovery.pem ./abc.txt Administrator@10.10.2.12:C:\deployment
        run:  |
          cp abc.txt ./ab.txt
          aws ssm start-session --target i-071a4716e15bd8b94
      - name: git
        run: |
          git init
      - name: Commit file
        run: |
          git config --local user.email "Vikrantchughimp@gmail.com"
          git config --local user.name "VikrantChugh"
          git add ab.txt
          git commit -a -m "Add changes"
          git push
        #   Copy-Item -Path ./ab.txt -Destination C:\deployment
