name: Testing
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]    
 
    
env:
  aws-region: us-east-1

jobs:
  runner:
    name: pipeline-test
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3
        # with: 
        #   repository: VikrantChugh/vikrant
        #   ref: 'main'
        #   token: ${{ secrets.TOKEN_GITHUB }}
          

        
      # - name: Copy file from git repo 
      #   run:  |
      #     cp McDOptimized.py ./ab.txt
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1   
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          Aws-region: ${{env.aws-region}}

      - name: Install Git Bash using Chocolatey
        run: |
           if (-not (Test-Path "C:\ProgramData\chocolatey\choco.exe")) {
           Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
           }
           choco install git -y

      - name: Run Git Bash command
        shell: bash
        run: |
              # Run Git Bash
              git --version
  
